#ifndef PROJET_S2_CDATAFRAME_FONCTIONSCOLONNES_H
#define PROJET_S2_CDATAFRAME_FONCTIONSCOLONNES_H

struct COLUMN
{
    char titre[50];
    int* T;
};

//PARTIE SABRINA

//PARTIE SIDNEY

#endif //PROJET_S2_CDATAFRAME_FONCTIONSCOLONNES_H
